name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install CocoaPods
        run: sudo gem install cocoapods
          
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Generate iOS project
        run: bunx expo prebuild --platform ios --clean

      - name: Install Pod dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace rn-reusable-sample.xcworkspace -scheme rn-reusable-sample -configuration Release -archivePath ./build/app.xcarchive archive CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath ./build/app.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath ./build || true

      - name: Find IPA files
        id: find-ipa
        run: |
          echo "Finding IPA files..."
          find . -name "*.ipa" -type f | tee ipa-files.txt
          echo "IPA files found:"
          cat ipa-files.txt

      - name: Create IPA from archive if no IPA found
        if: ${{ contains(steps.find-ipa.outputs.stdout, 'No such file') }}
        run: |
          cd ios/build
          mkdir -p Payload
          cp -r app.xcarchive/Products/Applications/rn-reusable-sample.app Payload/
          zip -r rn-reusable-sample.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: |
            ./ios/build/*.ipa
          retention-days: 7
